export const serviceGroups = [
  {
    title: "AI & Automation",
    description: "Intelligent tools that support customers, teams, and everyday decisions.",
    pages: ["ai", "chatbots", "voice-agents", "computer-vision", "automation"],
  },
  {
    title: "Web & Commerce",
    description: "Useful, polished digital experiences built around your audience.",
    pages: ["web-development", "ui-ux", "wordpress", "shopify", "seo"],
  },
  {
    title: "Infrastructure & Growth",
    description: "The hosting, visual identity, and marketing support behind a stronger presence.",
    pages: ["hosting", "graphic-design", "digital-marketing"],
  },
];

export const homeServices = [
  {
    number: "01",
    title: "Web Development",
    text: "Websites, stores, and digital products shaped around how your business works.",
    icon: "</>",
    details: "From platform selection and UX to launch and iteration, we build experiences that are straightforward to use and ready to grow.",
    highlights: ["Custom websites", "Online stores", "Web applications"],
    page: "web-development",
  },
  {
    number: "02",
    title: "AI & Automation",
    text: "Assistants and connected workflows that make routine work easier.",
    icon: "AI",
    details: "We explore where AI and automation can help, then design practical systems that fit your existing processes.",
    highlights: ["Chatbots", "Voice agents", "Workflow automation"],
    page: "ai",
  },
  {
    number: "03",
    title: "Brand & Growth",
    text: "Design and marketing that help people understand and remember your business.",
    icon: "✦",
    details: "A consistent visual identity and a clear growth plan give every customer touchpoint a stronger purpose.",
    highlights: ["Brand design", "SEO", "Digital marketing"],
    page: "graphic-design",
  },
];

export const pageContent = {
  about: {
    kicker: "ABOUT BAIG BOTS",
    title: "Ideas backed by people who build.",
    lead: "We bring design, development, AI, and growth thinking together to solve digital challenges with care and clarity.",
    introHeading: "A team for the whole digital journey.",
    intro: "Good digital work needs more than a single skill. We combine research, design, engineering, and practical business thinking to create experiences that feel intuitive and work hard for the people using them. Our approach starts with your goals and stays collaborative through delivery.",
    featuresHeading: "What guides our work",
    features: [
      { title: "Built around your needs", text: "We shape the scope around your audience, constraints, and goals instead of forcing a standard package." },
      { title: "Clear collaboration", text: "You stay close to the decisions, with regular updates and room to refine the work together." },
      { title: "From idea to launch", text: "Strategy, design, development, testing, and continued improvement can be planned as one connected effort." },
      { title: "Useful innovation", text: "We choose technology for the value it creates, whether that is a simpler workflow, better experience, or new capability." },
    ],
    processHeading: "How a project moves forward",
    process: [
      { title: "Discover", text: "We learn about your business, the problem, and the result you want." },
      { title: "Shape", text: "We agree on priorities, define a practical scope, and map the experience." },
      { title: "Build", text: "We design, develop, test, and prepare the solution for launch." },
      { title: "Improve", text: "We use feedback and real usage to decide what should evolve next." },
    ],
    related: ["services", "portfolio"],
  },
  portfolio: {
    kicker: "IDEAS IN ACTION",
    title: "Digital possibilities for different industries.",
    lead: "See how thoughtful design and technology can support commerce, manufacturing, energy, and emerging products.",
    introHeading: "Every challenge calls for its own approach.",
    intro: "The most useful work begins with a clear business need. These examples show the kinds of experiences we can shape, from product discovery and online shopping to industry websites and AI-enabled tools.",
    featuresHeading: "Types of work we can create",
    features: [
      { title: "Fashion commerce", text: "A browsing and shopping journey that lets a varied product collection shine." },
      { title: "Manufacturing websites", text: "Clear product information and a stronger digital presence for specialist makers." },
      { title: "Energy solutions", text: "An easy-to-follow presentation of technical services and their practical value." },
      { title: "Large online catalogs", text: "Product organization that helps shoppers find, compare, and choose." },
      { title: "AI experiences", text: "Connected tools that make complex information easier to use." },
      { title: "Lifestyle brands", text: "Visual storytelling that gives a product range a distinct online voice." },
    ],
    related: ["web-development", "ai", "graphic-design"],
  },
  ai: {
    kicker: "AI SOLUTIONS",
    title: "Make intelligent technology useful.",
    lead: "We help turn AI opportunities into connected experiences that support customers, improve workflows, and reveal useful insights.",
    introHeading: "AI should serve a clear purpose.",
    intro: "The right AI solution starts with a real task: answering a question, handling a call, understanding an image, or helping a team make sense of information. We explore the fit, shape the workflow, and connect the result to the tools people already use.",
    featuresHeading: "Where AI can help",
    features: [
      { title: "Customer conversations", text: "Assistants can respond to common questions and guide people toward the next useful step." },
      { title: "Voice experiences", text: "Natural voice interactions can support callers, route requests, and help with scheduling." },
      { title: "Visual intelligence", text: "Image and video analysis can surface patterns that are difficult to review manually." },
      { title: "Decision support", text: "Structured data and analytics can make trends easier to understand and act on." },
    ],
    processHeading: "From opportunity to working solution",
    process: [
      { title: "Identify", text: "Choose a business problem with a clear outcome." },
      { title: "Design", text: "Map data, user needs, and the right human handoffs." },
      { title: "Integrate", text: "Connect the solution to existing channels and systems." },
      { title: "Refine", text: "Review performance and improve the experience over time." },
    ],
    related: ["chatbots", "voice-agents", "computer-vision", "automation"],
  },
  chatbots: {
    kicker: "AI CHATBOTS",
    title: "Helpful answers, whenever customers ask.",
    lead: "Give visitors a faster route to information with a conversational assistant designed around your business.",
    introHeading: "Support that feels connected.",
    intro: "A chatbot can answer recurring questions, guide visitors through services, and hand more complex conversations to your team. We shape its language and knowledge around your brand, then connect it to the channels where customers already reach you.",
    featuresHeading: "Chatbot capabilities",
    features: [
      { title: "Business-specific knowledge", text: "Ground responses in your approved information so answers stay relevant." },
      { title: "Across channels", text: "Bring the same helpful experience to a website, app, or messaging platform." },
      { title: "Multiple languages", text: "Plan conversations for the audiences and regions your business serves." },
      { title: "Ongoing improvement", text: "Review common questions and refine answers as your services change." },
    ],
    related: ["ai", "voice-agents", "automation"],
  },
  "voice-agents": {
    kicker: "AI VOICE AGENTS",
    title: "A smarter first response to every call.",
    lead: "Voice agents can help callers get answers, arrange appointments, and reach the right person with less waiting.",
    introHeading: "Natural conversations with a clear purpose.",
    intro: "We design voice experiences around common caller needs and your existing support process. The agent can draw from an approved knowledge base, gather relevant details, and pass the conversation to a team member when a human response is needed.",
    featuresHeading: "Designed for real call flows",
    features: [
      { title: "Current information", text: "Connect the agent to maintained business knowledge and review its answers regularly." },
      { title: "Thoughtful transfers", text: "Pass context to your team so callers do not need to repeat the same story." },
      { title: "Appointment support", text: "Help callers find a suitable time and connect the result to scheduling tools." },
      { title: "Measured rollout", text: "Test common scenarios before launch, then monitor and improve the call experience." },
    ],
    related: ["ai", "chatbots", "automation"],
  },
  "computer-vision": {
    kicker: "COMPUTER VISION",
    title: "Find meaning in images and video.",
    lead: "Visual AI can help teams detect, classify, and review information at a scale that manual inspection cannot easily match.",
    introHeading: "Turn visual data into useful signals.",
    intro: "Computer vision systems can support quality checks, asset monitoring, inventory awareness, and other visual workflows. The right use case depends on the images available, the decisions to make, and the level of human review required.",
    featuresHeading: "Possible applications",
    features: [
      { title: "Image analysis", text: "Identify and organize objects or visual patterns in approved image sets." },
      { title: "Video insights", text: "Review events and activity in footage where there is a clear operational need." },
      { title: "Quality checks", text: "Surface potential defects or inconsistencies for a team to verify." },
      { title: "Industry workflows", text: "Explore fit across manufacturing, retail, agriculture, and other visual environments." },
    ],
    related: ["ai", "automation"],
  },
  automation: {
    kicker: "WORKFLOW AUTOMATION",
    title: "Give repetitive work a better path.",
    lead: "Connect tools and simplify repeatable processes so your team has more time for the work that needs its attention.",
    introHeading: "Start with the bottleneck.",
    intro: "Automation is most useful when it removes a real point of friction. We map the current process, define safe handoffs, and connect the systems involved. The result should be easier to understand, maintain, and improve.",
    featuresHeading: "What we can streamline",
    features: [
      { title: "System connections", text: "Move information between the applications your team relies on." },
      { title: "Customer handoffs", text: "Route requests and relevant context to the right people." },
      { title: "Routine updates", text: "Reduce repeated data entry and status chasing." },
      { title: "Clear oversight", text: "Keep important decisions visible and within your team's control." },
    ],
    related: ["ai", "chatbots", "web-development"],
  },
  "web-development": {
    kicker: "WEB DEVELOPMENT",
    title: "A website built for the way you grow.",
    lead: "From a focused business site to a more complex digital platform, we create experiences that are clear, responsive, and ready to evolve.",
    introHeading: "Choose the right foundation.",
    intro: "A successful website makes it easy for people to understand your offer and take the next step. We help select a suitable platform, plan the information, build the experience, and test it across devices before launch.",
    featuresHeading: "A complete web experience",
    features: [
      { title: "Purposeful structure", text: "Organize pages and content around what visitors need to know." },
      { title: "Responsive design", text: "Make the experience usable across phones, tablets, and larger screens." },
      { title: "Scalable build", text: "Plan for new content, features, and integrations as the business changes." },
      { title: "AI-ready thinking", text: "Explore useful additions such as search, support, and personalized journeys when they fit the goal." },
    ],
    processHeading: "From brief to launch",
    process: [
      { title: "Plan", text: "Define the audience, pages, and measures of success." },
      { title: "Design", text: "Shape the visual system and key user journeys." },
      { title: "Develop", text: "Build and integrate the agreed features." },
      { title: "Test", text: "Check usability, performance, and behavior across devices." },
    ],
    related: ["ui-ux", "wordpress", "shopify", "seo"],
  },
  "ui-ux": {
    kicker: "UI / UX DESIGN",
    title: "Make every interaction feel easier.",
    lead: "We turn complex tasks into digital journeys people can understand and use with confidence.",
    introHeading: "Design begins with the user.",
    intro: "Whether you are planning a new product or improving an existing one, clear navigation and thoughtful details matter. We study the goals behind each journey, shape the interface, and refine it through feedback.",
    featuresHeading: "Design that serves the task",
    features: [
      { title: "User journeys", text: "Map how people find information and complete important actions." },
      { title: "Interface design", text: "Create a consistent visual language for screens and components." },
      { title: "Prototypes", text: "Test key ideas before committing to a full build." },
      { title: "Practical refinement", text: "Use feedback to remove friction and make the experience clearer." },
    ],
    related: ["web-development", "graphic-design"],
  },
  wordpress: {
    kicker: "WORDPRESS WEBSITES",
    title: "A flexible site your team can manage.",
    lead: "Build a WordPress presence that brings together clear content, a distinct identity, and a straightforward editing experience.",
    introHeading: "Built for your content and your visitors.",
    intro: "WordPress can be a useful foundation for a site that needs regular publishing and easy updates. We plan the page structure, design the presentation, and set up the editing approach around the people who will maintain it.",
    featuresHeading: "What matters in the build",
    features: [
      { title: "Clear page structure", text: "Make services, stories, and calls to action easy to find." },
      { title: "Brand-consistent design", text: "Carry your visual language across templates and content blocks." },
      { title: "Easy updates", text: "Give your team a practical way to keep information current." },
      { title: "Performance basics", text: "Pay attention to responsive behavior, page weight, and essential SEO setup." },
    ],
    related: ["web-development", "ui-ux", "seo", "hosting"],
  },
  shopify: {
    kicker: "SHOPIFY STORES",
    title: "Make shopping simple from first look to checkout.",
    lead: "Create a store that presents products clearly and gives customers a confident route to purchase.",
    introHeading: "Commerce needs clarity.",
    intro: "A strong online store helps people discover products, compare options, and complete an order without confusion. We shape the storefront around your catalog, brand, and the journeys that matter most.",
    featuresHeading: "Storefront essentials",
    features: [
      { title: "Product discovery", text: "Organize collections and navigation so shoppers can find the right item." },
      { title: "Brand presentation", text: "Use clear imagery, copy, and layout to tell the product story." },
      { title: "Mobile shopping", text: "Keep browsing and buying comfortable on smaller screens." },
      { title: "Room to grow", text: "Plan for new products, campaigns, and integrations as demand changes." },
    ],
    related: ["web-development", "ui-ux", "digital-marketing"],
  },
  seo: {
    kicker: "SEO & SPEED",
    title: "Help the right people find your site.",
    lead: "Improve search visibility and website performance with a plan grounded in your audience and business goals.",
    introHeading: "Visibility takes useful work over time.",
    intro: "Search optimization starts with understanding what people look for and how your site answers them. We review technical health, content, page structure, and performance, then prioritize improvements that can be measured and refined.",
    featuresHeading: "A practical optimization plan",
    features: [
      { title: "Site audit", text: "Identify technical and content issues that may hold the site back." },
      { title: "Search intent", text: "Research the questions and terms your audience actually uses." },
      { title: "Page improvements", text: "Align content, metadata, and internal links with useful topics." },
      { title: "Performance review", text: "Track visibility, traffic, and page speed to guide the next changes." },
    ],
    processHeading: "How we improve search",
    process: [
      { title: "Assess", text: "Review current pages, competitors, and technical health." },
      { title: "Prioritize", text: "Choose the opportunities that match your goals." },
      { title: "Implement", text: "Improve the site and content in manageable stages." },
      { title: "Measure", text: "Use results to refine the ongoing plan." },
    ],
    related: ["web-development", "digital-marketing"],
  },
  hosting: {
    kicker: "CLOUD HOSTING",
    title: "A dependable home for your digital work.",
    lead: "Choose hosting that fits the application, traffic, and level of control your team needs.",
    introHeading: "The right setup makes growth easier.",
    intro: "A site or application needs a stable foundation behind the visible experience. We help evaluate hosting options, plan the setup, and keep performance, security, and maintenance in view.",
    featuresHeading: "Hosting options to explore",
    features: [
      { title: "Website hosting", text: "A straightforward environment for a business website and its day-to-day needs." },
      { title: "WordPress hosting", text: "A setup considered for WordPress updates, performance, and management." },
      { title: "VPS hosting", text: "More control and resources for applications with specific requirements." },
      { title: "Commerce and AI workloads", text: "Infrastructure choices shaped around stores, assistants, or other demanding tools." },
    ],
    related: ["web-development", "wordpress", "shopify", "ai"],
  },
  "graphic-design": {
    kicker: "GRAPHIC DESIGN",
    title: "Give your brand a visual voice.",
    lead: "Create design that makes your business recognizable across digital and physical touchpoints.",
    introHeading: "Good visuals make the message clearer.",
    intro: "A consistent visual system helps people understand who you are and what you offer. We connect creative decisions to your audience and goals, from the first logo exploration to campaign and product materials.",
    featuresHeading: "Design across touchpoints",
    features: [
      { title: "Identity", text: "Logo, color, typography, and a consistent direction for your brand." },
      { title: "Marketing materials", text: "Graphics for campaigns, presentations, and social channels." },
      { title: "Print and packaging", text: "Thoughtful layouts for brochures, merchandise, and product presentation." },
      { title: "Digital assets", text: "Visuals that support a cohesive website and product experience." },
    ],
    related: ["ui-ux", "digital-marketing", "portfolio"],
  },
  "digital-marketing": {
    kicker: "DIGITAL MARKETING",
    title: "Connect your message to measurable growth.",
    lead: "Bring strategy, creative work, and performance insight together across the channels your audience uses.",
    introHeading: "A plan that starts with the business goal.",
    intro: "Effective marketing is more than activity across many channels. We focus on the audience, the message, and the result to pursue, then use data to understand what is working and where to improve.",
    featuresHeading: "Connected marketing work",
    features: [
      { title: "Growth strategy", text: "Set priorities for campaigns, content, and customer journeys." },
      { title: "Search and content", text: "Help useful information reach people when they need it." },
      { title: "Paid and social channels", text: "Plan creative messages for relevant platforms and audiences." },
      { title: "Measurement", text: "Review performance and use the findings to sharpen the next step." },
    ],
    related: ["seo", "graphic-design", "web-development"],
  },
};
